spring:
  datasource:
    jdbcUrl: jdbc:postgresql://186.202.136.88:15480/metropolis
    username: postgres
    password: metro

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.jdbc.batch_size: 50
      hibernate.type: trace
      hibernate.use_sql_comments: true
      hibernate.showsql: false      
      hibernate.format_sql: true   

      
