package  br.com.edza.cjus.enums;

public enum ParametroEnum {

	SERVIDOR_INCLUI_ALTERA_BOLETO_EM_EXECUCAO_1(1),
	ALTERA_BOLETO_HABILITADO_2(2),
	ALTERA_BOLETO_INTERVALO_EXECUCAO_3(3), 
	ALTERA_BOLETO_ULTIMA_EXECUCAO_4(4),
	SERVIDOR_CONSULTA_BOLETO_EM_EXECUCAO_5(5),
	CONSULTA_BOLETO_HABILITADO_6(6),
	CONSULTA_BOLETO_INTERVALO_EXECUCAO_7(7), 
	CONSULTA_BOLETO_ULTIMA_EXECUCAO_8(8),
	SERVIDOR_BAIXA_BOLETO_EM_EXECUCAO_9(9),
	BAIXA_BOLETO_HABILITADO_10(10),
	BAIXA_BOLETO_INTERVALO_EXECUCAO_11(11), 
	BAIXA_BOLETO_ULTIMA_EXECUCAO_12(12),
	PJE_HABILITADO_13(13),
	PJE_INTERVALO_EXECUCAO_14(14), 
	PJE_ULTIMA_EXECUCAO_15(15),
	PJE__SERVIDOR_EM_EXECUCAO_16(16);


    private int id;

    private ParametroEnum(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }

}
