
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package br.jus.cnj.servico_intercomunicacao_2_2_2;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-27T18:47:13.764-03:00
 * Generated source version: 3.3.6
 *
// */
//
//@javax.jws.WebService(
//                      serviceName = "servico-intercomunicacao-2.2.2",
//                      portName = "servico-intercomunicacao-2.2.2SOAP",
//                      targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/",
//                      wsdlLocation = "file:/C:/Users/jwald/AppData/Local/Temp/tempdir2426621086743741512.tmp/servico-intercomunicacao-2.2.2_1.wsdl",
//                      endpointInterface = "br.jus.cnj.servico_intercomunicacao_2_2_2.ServicoIntercomunicacao222")

public class ServicoIntercomunicacao222SOAPImpl implements ServicoIntercomunicacao222 {

    private static final Logger LOG = Logger.getLogger(ServicoIntercomunicacao222SOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see br.jus.cnj.servico_intercomunicacao_2_2_2.ServicoIntercomunicacao222#consultarAlteracao(java.lang.String idConsultante, java.lang.String senhaConsultante, java.lang.String numeroProcesso, java.lang.Boolean sucesso, java.lang.String mensagem, java.lang.String hashCabecalho, java.lang.String hashMovimentacoes, java.lang.String hashDocumentos)*
     */
    public void consultarAlteracao(java.lang.String idConsultante, java.lang.String senhaConsultante, java.lang.String numeroProcesso, javax.xml.ws.Holder<java.lang.Boolean> sucesso, javax.xml.ws.Holder<java.lang.String> mensagem, javax.xml.ws.Holder<java.lang.String> hashCabecalho, javax.xml.ws.Holder<java.lang.String> hashMovimentacoes, javax.xml.ws.Holder<java.lang.String> hashDocumentos) {
        LOG.info("Executing operation consultarAlteracao");
        try {
            java.lang.Boolean sucessoValue = null;
            sucesso.value = sucessoValue;
            java.lang.String mensagemValue = "";
            mensagem.value = mensagemValue;
            java.lang.String hashCabecalhoValue = "";
            hashCabecalho.value = hashCabecalhoValue;
            java.lang.String hashMovimentacoesValue = "";
            hashMovimentacoes.value = hashMovimentacoesValue;
            java.lang.String hashDocumentosValue = "";
            hashDocumentos.value = hashDocumentosValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.jus.cnj.servico_intercomunicacao_2_2_2.ServicoIntercomunicacao222#consultarAvisosPendentes(java.lang.String idRepresentado, java.lang.String idConsultante, java.lang.String senhaConsultante, java.lang.String dataReferencia, java.lang.Boolean sucesso, java.lang.String mensagem, java.util.List<br.jus.cnj.intercomunicacao_2_2.TipoAvisoComunicacaoPendente> aviso)*
     */
    public void consultarAvisosPendentes(java.lang.String idRepresentado, java.lang.String idConsultante, java.lang.String senhaConsultante, java.lang.String dataReferencia, javax.xml.ws.Holder<java.lang.Boolean> sucesso, javax.xml.ws.Holder<java.lang.String> mensagem, javax.xml.ws.Holder<java.util.List<br.jus.cnj.intercomunicacao_2_2.TipoAvisoComunicacaoPendente>> aviso) {
        LOG.info("Executing operation consultarAvisosPendentes");
        try {
            java.lang.Boolean sucessoValue = null;
            sucesso.value = sucessoValue;
            java.lang.String mensagemValue = "";
            mensagem.value = mensagemValue;
            java.util.List<br.jus.cnj.intercomunicacao_2_2.TipoAvisoComunicacaoPendente> avisoValue = null;
            aviso.value = avisoValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.jus.cnj.servico_intercomunicacao_2_2_2.ServicoIntercomunicacao222#confirmarRecebimento(java.lang.String idRecebedor, java.lang.String senhaRecebedor, java.lang.String protocolo, java.lang.Boolean sucesso, java.lang.String mensagem)*
     */
    public void confirmarRecebimento(java.lang.String idRecebedor, java.lang.String senhaRecebedor, java.lang.String protocolo, javax.xml.ws.Holder<java.lang.Boolean> sucesso, javax.xml.ws.Holder<java.lang.String> mensagem) {
        LOG.info("Executing operation confirmarRecebimento");
        try {
            java.lang.Boolean sucessoValue = null;
            sucesso.value = sucessoValue;
            java.lang.String mensagemValue = "";
            mensagem.value = mensagemValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.jus.cnj.servico_intercomunicacao_2_2_2.ServicoIntercomunicacao222#consultarTeorComunicacao(br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConsultarTeorComunicacao parameters)*
     */
    public br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConsultarTeorComunicacaoResposta consultarTeorComunicacao(br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConsultarTeorComunicacao parameters) {
        LOG.info("Executing operation consultarTeorComunicacao");
        try {
            br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConsultarTeorComunicacaoResposta _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.jus.cnj.servico_intercomunicacao_2_2_2.ServicoIntercomunicacao222#consultarProcesso(br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConsultarProcesso parameters)*
     */
    public br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConsultarProcessoResposta consultarProcesso(br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConsultarProcesso parameters) {
        LOG.info("Executing operation consultarProcesso");
        try {
            br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoConsultarProcessoResposta _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.jus.cnj.servico_intercomunicacao_2_2_2.ServicoIntercomunicacao222#entregarManifestacaoProcessual(br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoEntregarManifestacaoProcessual parameters)*
     */
    public br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoEntregarManifestacaoProcessualResposta entregarManifestacaoProcessual(br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoEntregarManifestacaoProcessual parameters) {
        LOG.info("Executing operation entregarManifestacaoProcessual");
        try {
            br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoEntregarManifestacaoProcessualResposta _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
