package br.jus.cnj.servico_intercomunicacao_2_2_2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.apache.cxf.interceptor.InInterceptors;
import org.apache.cxf.interceptor.OutInterceptors;



/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-27T18:47:13.801-03:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", name = "servico-intercomunicacao-2.2.2")
@XmlSeeAlso({br.jus.cnj.intercomunicacao_2_2.ObjectFactory.class, br.jus.cnj.tipos_servico_intercomunicacao_2_2.ObjectFactory.class, br.jus.cnj.servico_intercomunicacao_2_2.ObjectFactory.class, br.jus.cnj.mni.cda.ObjectFactory.class})
@InInterceptors(interceptors = "org.apache.cxf.interceptor.LoggingInInterceptor")
@OutInterceptors(interceptors = "org.apache.cxf.interceptor.LoggingOutInterceptor")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServicoIntercomunicacao222 {

    /**
     * Operação destinada a permitir a entrega de
     * 				manifestação processual por órgão de representação processual ou por
     * 				advogado.
     * 				Essa operação também permite a entrega de petição inicial.
     */
    @WebMethod(action = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/entregarManifestacaoProcessual")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "entregarManifestacaoProcessualResposta", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", partName = "parameters")
    public br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoEntregarManifestacaoProcessualResposta entregarManifestacaoProcessual(

        @WebParam(partName = "parameters", name = "entregarManifestacaoProcessual", targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/")
        br.jus.cnj.tipos_servico_intercomunicacao_2_2.TipoEntregarManifestacaoProcessual parameters
    );
}
