package br.jus.cnj.servico_intercomunicacao_2_2_2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-27T18:47:13.809-03:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "servico-intercomunicacao-2.2.2",
                  wsdlLocation = "file:/C:/Users/jwald/AppData/Local/Temp/tempdir2426621086743741512.tmp/servico-intercomunicacao-2.2.2_1.wsdl",
                  targetNamespace = "http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/")
public class ServicoIntercomunicacao222_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", "servico-intercomunicacao-2.2.2");
    public final static QName ServicoIntercomunicacao222SOAP = new QName("http://www.cnj.jus.br/servico-intercomunicacao-2.2.2/", "servico-intercomunicacao-2.2.2SOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/jwald/AppData/Local/Temp/tempdir2426621086743741512.tmp/servico-intercomunicacao-2.2.2_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicoIntercomunicacao222_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/jwald/AppData/Local/Temp/tempdir2426621086743741512.tmp/servico-intercomunicacao-2.2.2_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicoIntercomunicacao222_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicoIntercomunicacao222_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicoIntercomunicacao222_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServicoIntercomunicacao222_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServicoIntercomunicacao222_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServicoIntercomunicacao222_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ServicoIntercomunicacao222
     */
    @WebEndpoint(name = "servico-intercomunicacao-2.2.2SOAP")
    public ServicoIntercomunicacao222 getServicoIntercomunicacao222SOAP() {
        return super.getPort(ServicoIntercomunicacao222SOAP, ServicoIntercomunicacao222.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicoIntercomunicacao222
     */
    @WebEndpoint(name = "servico-intercomunicacao-2.2.2SOAP")
    public ServicoIntercomunicacao222 getServicoIntercomunicacao222SOAP(WebServiceFeature... features) {
        return super.getPort(ServicoIntercomunicacao222SOAP, ServicoIntercomunicacao222.class, features);
    }

}
